# Generated by Django 4.2.2 on 2023-06-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('after_discount', models.IntegerField()),
                ('photo', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=10000)),
                ('ratting', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colors', models.CharField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('total_review', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=500)),
                ('review', models.TextField(max_length=3000)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_Api.product')),
            ],
        ),
    ]
