# Generated by Django 4.2.2 on 2023-07-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0004_catagory_section_product_catagorys_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='show_on_home',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='show_on_home',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
