# Generated by Django 4.2.2 on 2023-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0005_catagory_show_on_home_section_show_on_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('shop_poster', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('linkdin', models.CharField(max_length=200)),
                ('twiter', models.CharField(max_length=200)),
                ('instragram', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homeslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Spacialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
