# Generated by Django 4.2.2 on 2023-07-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0006_homepage_homeslider_spacialoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
