# Generated by Django 4.2.2 on 2023-07-29 06:15

import Basic_Api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0009_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Basic_Api.models.UserManager()),
            ],
        ),
    ]
