# Generated by Django 4.2.2 on 2023-08-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0013_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CategoryImage/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catagorys',
            field=models.ManyToManyField(blank=True, null=True, to='Basic_Api.catagory'),
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='SubCategoryImage/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_Api.catagory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_catagory',
            field=models.ManyToManyField(blank=True, null=True, to='Basic_Api.subcatagory'),
        ),
    ]
