# Generated by Django 4.2.2 on 2023-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0014_catagory_image_alter_product_catagorys_subcatagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacialoffer',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
