# Generated by Django 4.2.2 on 2023-08-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0016_product_buying_price_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
