# Generated by Django 4.2.2 on 2023-08-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0019_alter_user_options_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
