# Generated by Django 4.2.2 on 2023-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0021_user_balance_user_balance_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupun_code', models.CharField(max_length=200, unique=True)),
                ('offer_name', models.CharField(max_length=500)),
                ('price_condition', models.IntegerField()),
                ('discount_in_percentage', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
