# Generated by Django 4.2.2 on 2023-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0024_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
