# Generated by Django 4.2.2 on 2023-09-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0025_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='All_Product_Additional_Photo/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_Api.product')),
            ],
        ),
    ]
