# Generated by Django 4.2.2 on 2023-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0026_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagorys',
            field=models.ManyToManyField(to='Basic_Api.catagory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_catagory',
            field=models.ManyToManyField(to='Basic_Api.subcatagory'),
        ),
    ]
