# Generated by Django 4.2.2 on 2023-09-17 15:07

import Basic_Api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0027_alter_product_catagorys_alter_product_sub_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discription',
            field=Basic_Api.models.MyFroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tutorial',
            field=Basic_Api.models.MyFroalaField(blank=True, null=True),
        ),
    ]
