# Generated by Django 4.2.2 on 2023-09-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0029_alter_product_catagorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_catagory',
            field=models.ManyToManyField(blank=True, null=True, to='Basic_Api.subcatagory'),
        ),
    ]
