# Generated by Django 4.2.2 on 2023-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0030_alter_product_sub_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
