# Generated by Django 4.2.2 on 2023-10-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0031_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_forget_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
