# Generated by Django 4.2.2 on 2023-09-17 04:18

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='description',
        ),
        migrations.AddField(
            model_name='pages',
            name='content',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
