# Generated by Django 4.2.2 on 2023-09-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategory_blogtag_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_title',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
