# Generated by Django 4.2.2 on 2023-09-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_Api', '0030_alter_product_sub_catagory'),
        ('blog', '0007_pages_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='related_Product',
            field=models.ManyToManyField(blank=True, null=True, to='Basic_Api.product'),
        ),
        migrations.CreateModel(
            name='BlogItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_Api.product')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogitems'),
        ),
    ]
