# Generated by Django 4.2.2 on 2023-09-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_related_product_blogitems_blog_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='items',
        ),
        migrations.AddField(
            model_name='blogitems',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
