# Generated by Django 4.2.2 on 2023-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_cupon_order_delevary_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
