# Generated by Django 4.2.2 on 2023-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_billing_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sell_done',
            field=models.BooleanField(default=False),
        ),
    ]
